### ISSUE TITLE
Cannot evaluate the result of "Date.now()"

### ISSUE THREAD

**Issue by cheton** [browserify/static-eval#25]
Here is my code snippet:
```js
const evaluate = require('static-eval');
const parse = require('esprima').parse;

const src = 'Date.now()';
const ast = parse(src).body[0].expression;
const result = evaluate(ast, { Date: Date });

console.log(result);
```

The code `Date.now()` will produce an AST tree as shown below: 

```json
{
    "type": "Program",
    "body": [
        {
            "type": "ExpressionStatement",
            "expression": {
                "type": "CallExpression",
                "callee": {
                    "type": "MemberExpression",
                    "computed": false,
                    "object": {
                        "type": "Identifier",
                        "name": "Date"
                    },
                    "property": {
                        "type": "Identifier",
                        "name": "now"
                    }
                },
                "arguments": []
            }
        }
    ],
    "sourceType": "script"
}
```

After tracing into the code, I found that there was a security check added in the commit: https://github.com/browserify/static-eval/commit/c06f1b8c0a0cd1cc989c025fbb4c5776fc661c2c#diff-168726dbe96b3ce427e7fedce31bb0bcR101

Actually, the type of `Date` is a function, it will return FAIL and result in undefined result:

```js
// do not allow access to methods on Function 
if((obj === FAIL) || (typeof obj == 'function')){
    return FAIL;
}
```

Remove `typeof obj === 'function'` from if statement will definitely resolve this issue:
```js
if(obj === FAIL){
    return FAIL;
}
```

May I know if there is a security reason that should not allow callee object as a function?

**Comment by hanvyj** [comment]
Could you do `new Date()` as a workaround?

**Comment by goto-bus-stop** [comment]
> May I know if there is a security reason that should not allow callee object as a function?

Because `Date` is a function, `Date.constructor` is the `Function` constructor. That means `Date.constructor("arbitrary code")` allows arbitrary code execution. You could do `Date.constructor("console.log(process.env)")` to look at possibly private information, for example.

static-eval is never going to be able to 100% avoid that, and should not be used on untrusted input, but we try to guard against the obvious cases at least.
