### ISSUE TITLE
Inheritance error with Slack Node SDK and NCC

### ISSUE THREAD

**Issue by ataylorme** [browserify/static-eval#33]
Hello,
I'm updating dependencies in my project (yay!) but I'm having some issues with [the Slack Node SDK](https://github.com/slackapi/node-slack-sdk) and [`@vercel/ncc`](https://github.com/vercel/ncc).

I am maintaining a serverless function that reacts to interactive Slack messages. I am using the Slack SDK in a TypeScript environment, compiling my code with `ncc` for deployment to AWS Lambda.

Updating `ncc` also updates `static-eval`, which throws a new error when running my compiled Lambda function.

Going through the change logs between the old and new versions I believe this was introduced in #27

The error I am seeing is `Error: Attempt to inherit from WebClient methods without inheriting from WebClient`

Here is how I am using the Slack SDK:

```js
import {WebClient as SlackWebClient} from '@slack/web-api'
(async () => {
  // The slack token is fetched from SSM
  const {slackToken} = await getSecrets({environment})
  const slackClient = new SlackWebClient(slackToken)
  await slackClient.chat.postMessage({
    channel: channelID,
    thread_ts: messageID,
    text: `Some message text`,
  })
})
```

which aligns with their [Posting a message with Web API documentation](https://github.com/slackapi/node-slack-sdk#posting-a-message-with-web-api)

If you can point me in the right direction on how to resolve this I would appreciate it.

**Comment by goto-bus-stop** [comment]
Looking at ncc's lockfile, static-eval is _only_ installed through their `pdfkit` dependency, which is _only_ installed for tests and not for end users. As such, I don't think this error can possibly be related to static-eval.

**Comment by ataylorme** [comment]
@goto-bus-stop thanks for the reply. I think you are correct -- I did some more debugging and compiling my code with TypeScript only (without `ncc`) does **not** throw this error.

The error comes from the Slack SDK: https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/methods.ts#L37
